### ISSUE TITLE
ValueError null

### ISSUE THREAD

**Issue by masterlexa** [toluaina/pg-sync#18]
PGSync version: 1.1.1

Postgres version: 9.6

Elasticsearch version: 7.7.1

Redis version: latest

Python version: 3.7

Problem Description: 

ValueError: invalid literal for int() with base 10: 'null'
When it syncs null values.

Full traceback:
Traceback (most recent call last):
  File "/Users/masterlexa/PycharmProjects/venv/bin/pgsync", line 7, in <module>
    sync.main()
  File "pgsync/utils.py", line 82, in pgsync.utils.timeit.timed
  File "/Users/masterlexa/PycharmProjects/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/masterlexa/PycharmProjects/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/masterlexa/PycharmProjects/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/masterlexa/PycharmProjects/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "pgsync/sync.py", line 791, in pgsync.sync.main
  File "pgsync/sync.py", line 742, in pgsync.sync.Sync.pull
  File "pgsync/sync.py", line 143, in pgsync.sync.Sync.logical_slot_changes
  File "pgsync/sync.py", line 138, in pgsync.sync.Sync.logical_slot_changes
  File "pgsync/base.py", line 577, in pgsync.base.Base.parse_logical_slot
  File "pgsync/base.py", line 515, in _parse_logical_slot
  File "pgsync/base.py", line 473, in pgsync.base.Base.parse_value
  File "pgsync/base.py", line 471, in pgsync.base.Base.parse_value
ValueError: invalid literal for int() with base 10: 'null'

```

**Comment by toluaina** [comment]
This too is resolved in version 1.1.2
