### ISSUE TITLE
Trouble with Trigger (pg_notify())

### ISSUE THREAD

**Issue by masterlexa** [toluaina/pg-sync#19]
PGSync version: 1.1.1

Postgres version: 9.6

Elasticsearch version: 7.7.1

Redis version: latest

Python version: 3.7

Problem Description: 
Problem with a column that contains a big type.
In the official documentation, the payload has a limit of 8000 bytes.
https://www.postgresql.org/docs/9.0/sql-notify.html

Error Message (if any): 

```
ERROR:  payload string too long
КОНТЕКСТ:  SQL statement "SELECT PG_NOTIFY(channel, notification::TEXT)"
PL/pgSQL function table_notify() line 37 at PERFORM
```

**Comment by toluaina** [comment]
Thanks for finding this. 
This is also resolved in version 1.1.2

**Comment by masterlexa** [comment]
Exception in thread Thread-53:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "pgsync/sync.py", line 641, in pgsync.sync.Sync.poll_redis
  File "pgsync/redisqueue.py", line 73, in pgsync.redisqueue.RedisQueue.bulk_pop
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by toluaina** [comment]
Can you try with version 1.1.3 and see if this resolve this
