### ISSUE TITLE
SQLAlchemy err: Neither 'BooleanClauseList' object nor 'Comparator' object has an attribute '_orig'

### ISSUE THREAD

**Issue by sivy** [toluaina/pg-sync#29]
PGSync version: 1.1.6

SQLAlchemy version: 1.3.18

Postgres version: 9.6.8

Elasticsearch version: latest

Redis version: latest

Python version: 3.7

Problem Description: Syncing throws the listed error in logs, I can't be sure yet why it's doing this. Having no access to the actual sync source code makes it hard to troubleshoot.

Error Message (if any): 

```
Polling db pmx_test: 3 items <= Cache
2020-08-13 13:59:47.819:ERROR:pgsync.sync: Exception Neither 'BooleanClauseList' object nor 'Comparator' object has an attribute '_orig'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 744, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute '_orig'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pgsync/sync.py", line 572, in pgsync.sync.Sync._sync
  File "pgsync/query_builder.py", line 746, in pgsync.query_builder.QueryBuilder.build_queries
  File "pgsync/query_builder.py", line 249, in pgsync.query_builder.QueryBuilder._children
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 755, in __getattr__
    replace_context=err,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
AttributeError: Neither 'BooleanClauseList' object nor 'Comparator' object has an attribute '_orig'
2020-08-13 13:59:47.918:ERROR:pgsync.sync: Exception: Neither 'BooleanClauseList' object nor 'Comparator' object has an attribute '_orig'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 744, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute '_orig'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pgsync/sync.py", line 644, in pgsync.sync.Sync.sync_payloads
  File "pgsync/elastichelper.py", line 59, in pgsync.elastichelper.ElasticHelper.bulk
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 425, in parallel_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 140, in _helper_reraises_exception
    raise ex
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 292, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 128, in _chunk_actions
    for action, data in actions:
  File "pgsync/sync.py", line 575, in _sync
  File "pgsync/sync.py", line 572, in pgsync.sync.Sync._sync
  File "pgsync/query_builder.py", line 746, in pgsync.query_builder.QueryBuilder.build_queries
  File "pgsync/query_builder.py", line 249, in pgsync.query_builder.QueryBuilder._children
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 755, in __getattr__
    replace_context=err,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
AttributeError: Neither 'BooleanClauseList' object nor 'Comparator' object has an attribute '_orig'
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 744, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute '_orig'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "pgsync/sync.py", line 677, in pgsync.sync.Sync.poll_redis
  File "pgsync/sync.py", line 744, in pgsync.sync.Sync.on_publish
  File "pgsync/sync.py", line 650, in pgsync.sync.Sync.sync_payloads
  File "pgsync/sync.py", line 644, in pgsync.sync.Sync.sync_payloads
  File "pgsync/elastichelper.py", line 59, in pgsync.elastichelper.ElasticHelper.bulk
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 425, in parallel_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 140, in _helper_reraises_exception
    raise ex
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 292, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 128, in _chunk_actions
    for action, data in actions:
  File "pgsync/sync.py", line 575, in _sync
  File "pgsync/sync.py", line 572, in pgsync.sync.Sync._sync
  File "pgsync/query_builder.py", line 746, in pgsync.query_builder.QueryBuilder.build_queries
  File "pgsync/query_builder.py", line 249, in pgsync.query_builder.QueryBuilder._children
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 755, in __getattr__
    replace_context=err,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
AttributeError: Neither 'BooleanClauseList' object nor 'Comparator' object has an attribute '_orig'
```

**Comment by toluaina** [comment]
the source will be released soon.
Can you possibly provide the database schema for pmx_test and the pgsync config?

**Comment by sivy** [comment]
Hello,

I removed a bunch of columns from my `schema.json` and got it working again, so I'm going to carefully add columns until I trigger this again, and will return here with more info. Thanks!

**Comment by sivy** [comment]
I cannot share the entire schema, but I was able to reproduce the error when including a Boolean column from the PG schema in the schema for PGSync:

```
from sqlalchemy.types import Boolean
from sqlalchemy.schema import Table, Column

mytable = Table(
  "mytable",
  Column('bool_col', Boolean, default=False),
)
```

**Comment by toluaina** [comment]
thanks for this. Version 1.1.7 resolves this now.

**Comment by sivy** [comment]
Thanks!
