### ISSUE TITLE
Unable to set redis port via environment variable.

### ISSUE THREAD

**Issue by hellojustin** [toluaina/pg-sync#33]
PGSync version: 1.1.8

Postgres version: 12.4

Elasticsearch version: 7.9

Redis version: 5.0.9

Python version: 3.7

Problem Description: 

Hi @toluaina - I'm attempting to run pgsync in a docker container on Heroku. I'm using Heroku's redis add-on which uses a non-default port, so I must set the port in pgsync via the `REDIS_PORT` environment variable. While all the other env vars seem to properly set values for pgsync, `REDIS_PORT` doesn't seem to have an effect.

Here are the environment variables that are configured for my app:
![Screen Shot 2020-08-25 at 10 56 07 PM](https://user-images.githubusercontent.com/779730/91267118-7d4a8d00-e727-11ea-9ed1-be8d319eac15.png)

When the app runs, you can see that some variables (like `REDIS_HOST`, for example) seem to work, while `REDIS_PORT` does not. Rather than trying to connect to port 8629, pgsync attempts to connect to the default port 6379, and the connection is, of course, refused.
![Screen Shot 2020-08-25 at 11 02 46 PM](https://user-images.githubusercontent.com/779730/91266943-1e851380-e727-11ea-888b-ce2d54c5bae4.png)

Is it possible that the `REDIS_PORT` env var is not being passed to the redis client properly?

**Comment by hellojustin** [comment]
Following up.. to take Heroku completely out of the equation, I tested this locally in a docker container as well, and encountered the same problem. Here's the full output:
```sh
root@3ea0a63a444b:/# export ELASTICSEARCH_HOST=https://3cfb8b78dc4f6a3b3e36e1661bf1e4f7.us-east-1.aws.found.io
root@3ea0a63a444b:/# export ELASTICSEARCH_PORT=9243
root@3ea0a63a444b:/# export PG_HOST=ec2-54-157-11-238.compute-1.amazonaws.com
root@3ea0a63a444b:/# export PG_PASSWORD=pe0fc3e9a71c83bf0885667290b44cbe213d7e25ad00165e4ce0eca5f0615d0f0
root@3ea0a63a444b:/# export PG_PORT=5432
root@3ea0a63a444b:/# export PG_USER=u38kmr28qjfo2q
root@3ea0a63a444b:/# export REDIS_AUTH=h:p16ed5f81c737c9957733ceb9d2334b9de169b2dbf6b92cf8b101fd9286ad7747
root@3ea0a63a444b:/# export REDIS_DB=0
root@3ea0a63a444b:/# export REDIS_HOST=ec2-52-87-104-221.compute-1.amazonaws.com
root@3ea0a63a444b:/# export REDIS_PORT=8629
root@3ea0a63a444b:/# pgsync --config schema.json --daemon
2020-08-26 06:11:13.292:ERROR:pgsync.redisqueue: Redis server is not running: Error 111 connecting to ec2-52-87-104-221.compute-1.amazonaws.com:6379. Connection refused.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pgsync/redisqueue.py", line 33, in pgsync.redisqueue.RedisQueue.__init__
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to ec2-52-87-104-221.compute-1.amazonaws.com:6379. Connection refused.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pgsync", line 7, in <module>
    sync.main()
  File "pgsync/utils.py", line 81, in pgsync.utils.timeit.timed
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "pgsync/sync.py", line 854, in pgsync.sync.main
  File "pgsync/sync.py", line 61, in pgsync.sync.Sync.__init__
  File "pgsync/redisqueue.py", line 36, in pgsync.redisqueue.RedisQueue.__init__
  File "pgsync/redisqueue.py", line 33, in pgsync.redisqueue.RedisQueue.__init__
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1378, in ping
    return self.execute_command('PING')
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to ec2-52-87-104-221.compute-1.amazonaws.com:6379. Connection refused.
```

**Comment by toluaina** [comment]
You are totally right the Redis port was being ignored. I have pushed out 1.1.9 to address this.  thanks.

**Comment by hellojustin** [comment]
Wow @toluaina thanks for the quick follow up!
I'll give this another try tonight.
Really cool project btw!

**Comment by hellojustin** [comment]
Confirmed! I'm able to connect to Redis now. Closing this out. I really appreciate the help @toluaina!

**Comment by BenjamenMeyer** [comment]
@hellojustin just to follow-up - I know it's been two years now, but to confirm: were you able to get this working on Heroku? With a PG database and ES cluster via Heroku addons? Or was PG deployed in another manner? TIA

**Comment by LondonAppDev** [comment]
@BenjamenMeyer I'm wondering the same thing. Did you get it working using PostgreSQL on Heroku?

**Comment by LondonAppDev** [comment]
Thanks @BenjamenMeyer
